### ISSUE TITLE
#11번

### ISSUE THREAD

**Issue by yenapple** [Big-BlueBerry/JewishProblems#3]
sin10 이 무리수임을 증명해야 하는데 이 아이디어ㅏ 어떠냐
일단 난 0을 제외한 모든 유리수에서 사인값이 무리수임을 보일 거임
sin(x) = x-x^3/3! + x^5/5!-x^7/7!+..... 이때 k는 4로 나누면 1이 남는 홀수일 때 유한 부분합 S(k) 을 저기서  x-x^3/3! + x^5/5!-x^7/7!+ ...-x^(k-2)/(k-2)! 이렇게 정의하면 k!(sin(x) - S(k)) =x^k(1 - x^2/(k+1)(k+2) + x^4/(k+1)(k+2)(k+3)(k+4) - ....) 이 되고
x는 유리수이며 sin(x)가 무리수라고 가정하면 (sin(x) - S(k))는 유리수이므로  k를 충분히 크게 잡아서 좌변이 정수가 되게 만들 수 있음(sin(x) = p/q (p,q는 서로소) 이면 k> q로 두면 통분해둔 좌변의 분모가 k!에 의해 없어질테니까)
그런데 만약 0<=x<=1 인 유리수x이라면 우변은 1보다 항상 작을 수밖에 없음
x^2/(k+1)(k+2) > x^4/(k+1)(k+2)(k+3)(k+4) > x^6/(k+1)(k+2)(k+3)(k+4)(k+5)(k+6) ...이기 때문임(이건 이항 몇번으로 금방 보여짐)
따라서 좌변은 정수이고 우변은 1보다 작은 유리수이므로 모순.
0<=x<=1인 케이스는 일단 이렇게 증명해 봤는데 모든 유리수로 확장 가능할진 모르겠음

**Comment by yenapple** [comment]
저것 말고도 몇 개 Proof 방법을 고안해봤는데 저기서 확장하는 방법 말고도 infinite continued fraction의 값이 무리수라는 것을 이용하고 오일러 연분수 공식을 써서 증명해보는 것도 되게 괜찮을 거 같음

**Comment by 20chan** [comment]
sin10 = x 라 하면
sin30=3x-4x^3
이니까 방정식 풀면 x는 무리수

라고 쉽게 풀 수도 이씀
